<a href="https://colab.research.google.com/github/MathurUtkarsh/Word_Embedding/blob/main/Word_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Word Embedding Techniques using Embedding Layer in Keras**

In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of water',
     'the glass of protien shake',
     'A cup of cofee',
    'I am a bad liar',
     'I am a excellent developer',
     'understand the meaning of words',
    'If you know me then only you know me',]

In [3]:

sent

['the glass of water',
 'the glass of protien shake',
 'A cup of cofee',
 'I am a bad liar',
 'I am a excellent developer',
 'understand the meaning of words',
 'If you know me then only you know me']

In [4]:
### Vocabulary size
voc_size=10000

## One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[2536, 4889, 5217, 4587], [2536, 4889, 5217, 3739, 8390], [9665, 8507, 5217, 2831], [7220, 192, 9665, 8605, 9346], [7220, 192, 9665, 2715, 6332], [7078, 2536, 6511, 5217, 586], [1086, 1869, 3394, 4886, 62, 5217, 1869, 3394, 4886]]


# **Word Embedding Represntation**

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np


In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2536 4889 5217 4587]
 [   0    0    0 2536 4889 5217 3739 8390]
 [   0    0    0    0 9665 8507 5217 2831]
 [   0    0    0 7220  192 9665 8605 9346]
 [   0    0    0 7220  192 9665 2715 6332]
 [   0    0    0 7078 2536 6511 5217  586]
 [1869 3394 4886   62 5217 1869 3394 4886]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[-0.02941747 -0.00864368 -0.03850449  0.0336581  -0.01603704
   -0.01737305 -0.00215361  0.04433984  0.00610703  0.02164593]
  [-0.02941747 -0.00864368 -0.03850449  0.0336581  -0.01603704
   -0.01737305 -0.00215361  0.04433984  0.00610703  0.02164593]
  [-0.02941747 -0.00864368 -0.03850449  0.0336581  -0.01603704
   -0.01737305 -0.00215361  0.04433984  0.00610703  0.02164593]
  [-0.02941747 -0.00864368 -0.03850449  0.0336581  -0.01603704
   -0.01737305 -0.00215361  0.04433984  0.00610703  0.02164593]
  [-0.03973437  0.00027888  0.01196588  0.02276261  0.01592677
    0.01088749 -0.031472    0.00655043 -0.04242292 -0.02747439]
  [-0.01620454 -0.01242747  0.04777486  0.00792093  0.01217948
   -0.02791843  0.00571687 -0.04820808  0.00014683  0.03413786]
  [-0.03523502 -0.00577583 -0.03299016  0.00868033  0.03677584
    0.014026   -0.0076224   0.03948679 -0.03935225  0.01335487]
  [-0.0266721  -0.04705569  0.04232004  0.01981202 -0.00840563
   -0.02675237 -0.04664918 -0.00723338 -0.014380

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 2536, 4889, 5217, 4587], dtype=int32)

In [14]:
print(model.predict(embedded_docs)[0])

[[-0.02941747 -0.00864368 -0.03850449  0.0336581  -0.01603704 -0.01737305
  -0.00215361  0.04433984  0.00610703  0.02164593]
 [-0.02941747 -0.00864368 -0.03850449  0.0336581  -0.01603704 -0.01737305
  -0.00215361  0.04433984  0.00610703  0.02164593]
 [-0.02941747 -0.00864368 -0.03850449  0.0336581  -0.01603704 -0.01737305
  -0.00215361  0.04433984  0.00610703  0.02164593]
 [-0.02941747 -0.00864368 -0.03850449  0.0336581  -0.01603704 -0.01737305
  -0.00215361  0.04433984  0.00610703  0.02164593]
 [-0.03973437  0.00027888  0.01196588  0.02276261  0.01592677  0.01088749
  -0.031472    0.00655043 -0.04242292 -0.02747439]
 [-0.01620454 -0.01242747  0.04777486  0.00792093  0.01217948 -0.02791843
   0.00571687 -0.04820808  0.00014683  0.03413786]
 [-0.03523502 -0.00577583 -0.03299016  0.00868033  0.03677584  0.014026
  -0.0076224   0.03948679 -0.03935225  0.01335487]
 [-0.0266721  -0.04705569  0.04232004  0.01981202 -0.00840563 -0.02675237
  -0.04664918 -0.00723338 -0.01438013 -0.03031476]]
